app = "kkd-property"
primary_region = "sin"

[build]

[env]
  DATABASE_URL = "file:/data/prod.db"
  STORAGE_ROOT = "/data/storage"

[[mounts]]
  source = "kkd_property_data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
