import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { PrismaMariaDb } from "@prisma/adapter-mariadb";
import { PrismaClient } from "../../src/generated/prisma/client";
import {
  BACKUP_MODELS,
  SCHEMA_METADATA_FILENAME,
  SNAPSHOT_DIR_PATTERN,
  sqlLiteral,
} from "./backup-format";
import { buildSnapshotMetadata, inspectSchema, sha256 } from "./schema-metadata";
import { OperationalError } from "./operational-output";

const BACKUP_LOCK_DIRECTORY = ".pages-cms-backup.lock";
const PARTIAL_DIRECTORY_PREFIX = ".pages-cms-backup-partial-";

export type BackupSnapshotResult = {
  snapshot: string;
  databaseSqlSha256: string;
  schemaSha256: string;
  sourceTransactional: boolean;
  writesQuiesced: boolean;
  rowCounts: Readonly<Record<string, number>>;
  privateStorageCopied: boolean;
  databaseBytes: number;
  privateStorageBytes: number;
  totalBytes: number;
  prunedCount: number;
};

export type CreateBackupOptions = {
  environment: Readonly<Record<string, string | undefined>>;
  retentionEnabled?: boolean;
  onWarning?: (message: string) => void;
  now?: () => Date;
};

function directorySize(directory: string): number {
  return readdirSync(directory, { withFileTypes: true }).reduce((total, entry) => {
    const entryPath = path.join(directory, entry.name);
    return total + (entry.isDirectory() ? directorySize(entryPath) : statSync(entryPath).size);
  }, 0);
}

function timestampForFolder(date: Date): string {
  return date.toISOString().replace(/:/g, "-").split(".")[0];
}

async function buildDumpSql(
  database: PrismaClient,
  createdAt: string
): Promise<{ sql: string; counts: Record<string, number> }> {
  const counts: Record<string, number> = {};
  const lines: string[] = [
    "-- kkd_prop data-only backup — generated by scripts/backup-db.mts",
    `-- created: ${createdAt}`,
    "-- Restore with: npx tsx scripts/restore-db.mts <snapshot-dir> --confirm",
    "-- or import this file through phpMyAdmin (schema must already exist).",
    "SET FOREIGN_KEY_CHECKS=0;",
  ];

  for (const { table, delegate } of BACKUP_MODELS) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const rows: Record<string, any>[] = await (database as any)[delegate].findMany();
    counts[table] = rows.length;
    lines.push("", `-- ${table} (${rows.length} row(s))`, `DELETE FROM \`${table}\`;`);
    if (rows.length === 0) continue;

    const columns = Object.keys(rows[0]);
    const columnList = columns.map((column) => `\`${column}\``).join(", ");
    const chunkSize = 200;
    for (let index = 0; index < rows.length; index += chunkSize) {
      const values = rows
        .slice(index, index + chunkSize)
        .map((row) => `(${columns.map((column) => sqlLiteral(row[column])).join(", ")})`)
        .join(", ");
      lines.push(`INSERT INTO \`${table}\` (${columnList}) VALUES ${values};`);
    }
  }

  lines.push("", "SET FOREIGN_KEY_CHECKS=1;", "");
  return { sql: lines.join("\n"), counts };
}

function pruneSnapshots(
  backupRoot: string,
  currentSnapshot: string,
  retentionDaysEnvironment: string | undefined,
  onWarning: (message: string) => void
): number {
  if (!retentionDaysEnvironment) return 0;
  const retentionDays = Number(retentionDaysEnvironment);
  if (!Number.isFinite(retentionDays) || retentionDays <= 0) {
    onWarning(
      `BACKUP_RETENTION_DAYS="${retentionDaysEnvironment}" is not a positive number — skipping pruning`
    );
    return 0;
  }

  const cutoffMs = Date.now() - retentionDays * 24 * 60 * 60 * 1000;
  let prunedCount = 0;
  for (const entry of readdirSync(backupRoot, { withFileTypes: true })) {
    if (!entry.isDirectory() || !SNAPSHOT_DIR_PATTERN.test(entry.name)) continue;
    if (entry.name === currentSnapshot) continue;
    const entryPath = path.join(backupRoot, entry.name);
    if (statSync(entryPath).mtimeMs < cutoffMs) {
      rmSync(entryPath, { recursive: true, force: true });
      prunedCount += 1;
    }
  }
  return prunedCount;
}

export async function createBackupSnapshot(
  options: CreateBackupOptions
): Promise<BackupSnapshotResult> {
  const { environment } = options;
  const databaseUrl = environment.DATABASE_URL;
  if (!databaseUrl) throw new OperationalError("DATABASE_URL_MISSING");
  if (!databaseUrl.startsWith("mysql://")) throw new OperationalError("DATABASE_URL_INVALID");

  const backupRoot = path.resolve(process.cwd(), environment.BACKUP_ROOT ?? "./backups");
  const privateStoragePath = path.resolve(
    process.cwd(),
    environment.STORAGE_ROOT ?? "./storage",
    "private"
  );
  const writesQuiesced = environment.BACKUP_WRITES_QUIESCED === "true";
  const onWarning = options.onWarning ?? (() => undefined);
  const createdAt = (options.now?.() ?? new Date()).toISOString();
  const snapshot = timestampForFolder(new Date(createdAt));
  const finalDirectory = path.join(backupRoot, snapshot);

  mkdirSync(backupRoot, { recursive: true });
  const lockDirectory = path.join(backupRoot, BACKUP_LOCK_DIRECTORY);
  try {
    mkdirSync(lockDirectory);
  } catch (error) {
    if (
      typeof error === "object" &&
      error !== null &&
      "code" in error &&
      error.code === "EEXIST"
    ) {
      throw new OperationalError("BACKUP_IN_PROGRESS");
    }
    throw error;
  }

  let database: PrismaClient | undefined;
  let partialDirectory: string | undefined;
  try {
    database = new PrismaClient({ adapter: new PrismaMariaDb(databaseUrl) });
    if (existsSync(finalDirectory)) throw new OperationalError("BACKUP_SNAPSHOT_EXISTS");

    const sourcePreflight = await inspectSchema(database);
    if (!sourcePreflight.sourceTransactional && !writesQuiesced) {
      throw new OperationalError("BACKUP_WRITES_NOT_QUIESCED");
    }

    const { sql, counts, inspected } = await database.$transaction(
      async (transaction) => {
        const dump = await buildDumpSql(transaction as PrismaClient, createdAt);
        const schema = await inspectSchema(transaction, dump.counts);
        return { ...dump, inspected: schema };
      },
      { isolationLevel: "RepeatableRead", timeout: 120_000, maxWait: 10_000 }
    );
    const databaseSqlSha256 = sha256(sql);
    const metadata = buildSnapshotMetadata(inspected, {
      createdAt,
      writesQuiesced,
      databaseSqlSha256,
    });

    partialDirectory = mkdtempSync(path.join(backupRoot, PARTIAL_DIRECTORY_PREFIX));
    const databasePath = path.join(partialDirectory, "database.sql");
    writeFileSync(databasePath, sql, "utf8");
    writeFileSync(
      path.join(partialDirectory, SCHEMA_METADATA_FILENAME),
      `${JSON.stringify(metadata, null, 2)}\n`,
      "utf8"
    );

    const privateStorageCopied = existsSync(privateStoragePath);
    let privateStorageBytes = 0;
    if (privateStorageCopied) {
      const privateDestination = path.join(partialDirectory, "private");
      cpSync(privateStoragePath, privateDestination, { recursive: true });
      privateStorageBytes = directorySize(privateDestination);
    } else {
      onWarning("configured storage/private does not exist — skipping private copy");
    }

    const databaseBytes = statSync(databasePath).size;
    renameSync(partialDirectory, finalDirectory);
    partialDirectory = undefined;
    const prunedCount = options.retentionEnabled
      ? pruneSnapshots(backupRoot, snapshot, environment.BACKUP_RETENTION_DAYS, onWarning)
      : 0;

    return {
      snapshot,
      databaseSqlSha256,
      schemaSha256: metadata.schemaSha256,
      sourceTransactional: metadata.sourceTransactional,
      writesQuiesced: metadata.writesQuiesced,
      rowCounts: counts,
      privateStorageCopied,
      databaseBytes,
      privateStorageBytes,
      totalBytes: databaseBytes + privateStorageBytes,
      prunedCount,
    };
  } finally {
    try {
      await database?.$disconnect();
    } finally {
      if (partialDirectory) rmSync(partialDirectory, { recursive: true, force: true });
      rmSync(lockDirectory, { recursive: true, force: true });
    }
  }
}
