-- CreateTable
CREATE TABLE `HomePageContent` (
    `id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(40) NOT NULL DEFAULT 'home',
    `heroKickerTh` VARCHAR(191) NULL,
    `heroKickerEn` VARCHAR(191) NULL,
    `heroTitleWhiteTh` VARCHAR(191) NULL,
    `heroTitleWhiteEn` VARCHAR(191) NULL,
    `heroTitleGoldTh` VARCHAR(191) NULL,
    `heroTitleGoldEn` VARCHAR(191) NULL,
    `heroSubtitleTh` TEXT NULL,
    `heroSubtitleEn` TEXT NULL,
    `heroAltTh` VARCHAR(191) NULL,
    `heroAltEn` VARCHAR(191) NULL,
    `heroImageKey` VARCHAR(191) NULL,
    `ctaPrimaryLabelTh` VARCHAR(191) NULL,
    `ctaPrimaryLabelEn` VARCHAR(191) NULL,
    `ctaSecondaryLabelTh` VARCHAR(191) NULL,
    `ctaSecondaryLabelEn` VARCHAR(191) NULL,
    `quickContactLabelTh` VARCHAR(191) NULL,
    `quickContactLabelEn` VARCHAR(191) NULL,
    `proofLabelTh` VARCHAR(191) NULL,
    `proofLabelEn` VARCHAR(191) NULL,
    `proofTitleTh` VARCHAR(191) NULL,
    `proofTitleEn` VARCHAR(191) NULL,
    `proofItem1Th` VARCHAR(191) NULL,
    `proofItem1En` VARCHAR(191) NULL,
    `proofItem2Th` VARCHAR(191) NULL,
    `proofItem2En` VARCHAR(191) NULL,
    `proofItem3Th` VARCHAR(191) NULL,
    `proofItem3En` VARCHAR(191) NULL,
    `feature1LabelTh` VARCHAR(191) NULL,
    `feature1LabelEn` VARCHAR(191) NULL,
    `feature2LabelTh` VARCHAR(191) NULL,
    `feature2LabelEn` VARCHAR(191) NULL,
    `feature3LabelTh` VARCHAR(191) NULL,
    `feature3LabelEn` VARCHAR(191) NULL,
    `feature4LabelTh` VARCHAR(191) NULL,
    `feature4LabelEn` VARCHAR(191) NULL,
    `showLatestWorks` BOOLEAN NOT NULL DEFAULT true,
    `latestWorksHeadingTh` VARCHAR(191) NULL,
    `latestWorksHeadingEn` VARCHAR(191) NULL,
    `metric1LabelTh` VARCHAR(191) NULL,
    `metric1LabelEn` VARCHAR(191) NULL,
    `metric1ValueTh` VARCHAR(191) NULL,
    `metric1ValueEn` VARCHAR(191) NULL,
    `metric2LabelTh` VARCHAR(191) NULL,
    `metric2LabelEn` VARCHAR(191) NULL,
    `metric2ValueTh` VARCHAR(191) NULL,
    `metric2ValueEn` VARCHAR(191) NULL,
    `metric3LabelTh` VARCHAR(191) NULL,
    `metric3LabelEn` VARCHAR(191) NULL,
    `metric3ValueTh` VARCHAR(191) NULL,
    `metric3ValueEn` VARCHAR(191) NULL,
    `viewAllLabelTh` VARCHAR(191) NULL,
    `viewAllLabelEn` VARCHAR(191) NULL,
    `showServicesCta` BOOLEAN NOT NULL DEFAULT true,
    `servicesCtaBadgeTh` VARCHAR(191) NULL,
    `servicesCtaBadgeEn` VARCHAR(191) NULL,
    `servicesCtaTitleTh` VARCHAR(191) NULL,
    `servicesCtaTitleEn` VARCHAR(191) NULL,
    `servicesCtaTextTh` TEXT NULL,
    `servicesCtaTextEn` TEXT NULL,
    `servicesCtaLinkLabelTh` VARCHAR(191) NULL,
    `servicesCtaLinkLabelEn` VARCHAR(191) NULL,
    `showFaq` BOOLEAN NOT NULL DEFAULT true,
    `faqBadgeTh` VARCHAR(191) NULL,
    `faqBadgeEn` VARCHAR(191) NULL,
    `faqTitleTh` VARCHAR(191) NULL,
    `faqTitleEn` VARCHAR(191) NULL,
    `faqIntroTh` TEXT NULL,
    `faqIntroEn` TEXT NULL,
    `faqLineButtonLabelTh` VARCHAR(191) NULL,
    `faqLineButtonLabelEn` VARCHAR(191) NULL,
    `version` INTEGER NOT NULL DEFAULT 1,
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `HomePageContent_key_key`(`key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HomeFaqItem` (
    `id` VARCHAR(191) NOT NULL,
    `homePageContentId` VARCHAR(191) NOT NULL,
    `questionTh` VARCHAR(191) NOT NULL,
    `questionEn` VARCHAR(191) NOT NULL,
    `answerTh` TEXT NOT NULL,
    `answerEn` TEXT NOT NULL,
    `sortOrder` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `HomeFaqItem_homePageContentId_sortOrder_key`(`homePageContentId`, `sortOrder`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `HomeFaqItem` ADD CONSTRAINT `HomeFaqItem_homePageContentId_fkey` FOREIGN KEY (`homePageContentId`) REFERENCES `HomePageContent`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
